import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxWrapper from "./ReduxWrapper";

export const metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxWrapper>{children}</ReduxWrapper>
      </body>
    </html>
  );
}